### ISSUE TITLE
Add user profile page with high level details like recently added ingredients, recently tried cocktails

### ISSUE THREAD

**Issue by jacobnisnevich** [jacobnisnevich/bartenders-manual#19]

**Comment by john-patterson** [comment]
Status update: I have all the data piped into this page correctly, should just be styling left to go. I also want to go and decorate other places where users show up with a link to the profile page.

![image](https://user-images.githubusercontent.com/17716252/105642952-c2dbc500-5e41-11eb-9c90-9feef3d1ec36.png)

**Comment by john-patterson** [comment]
You can see the progress in commit: https://github.com/jacobnisnevich/bartenders-manual/commit/4fbdac7809cd3d95773c4719081c2269973e7b67
